name: Check remotely runnable
on:
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, edited, reopened, synchronize ]

jobs:
  check-remotely-runnable:
      runs-on: ubuntu-20.04
      steps:
        - name: Check remotely runnable
          uses: thepycoder/clearml-actions-check-remotely-runnable@main
          with:
            CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
            CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
            CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
            CLEARML_TIMEOUT: 10
            CLEARML_QUEUE: 'GPU Queue'