name: Detect model degradation
on:
  pull_request:
    branches: [ main ]
    types: [ assigned, opened, edited, reopened, synchronize ]

jobs:
  detect-model-degradation:
      runs-on: ubuntu-20.04
      steps:
        - name: Compare models
          uses: allegroai/clearml-actions-detect-model-degradation@main
          with:
            CLEARML_PROJECT: 'Github CICD' # CHANGE ME
            CLEARML_TASK_NAME: 'dummy_task' # CHANGE ME
            CLEARML_SCALAR_TITLE: 'Performance Metric' # CHANGE ME
            CLEARML_SCALAR_SERIES: 'Series 1' # CHANGE ME
            CLEARML_SCALAR_MIN_MAX: 'MAX' # CHANGE ME
            CLEARML_BEST_TAGNAME: 'BESTEST MODEL' # CHANGE ME (OR NOT ^^)
            CLEARML_SCALAR_THRESHOLD: 3 # CHANGE ME
            CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
            CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
            CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
          env:
            COMMIT_ID: ${{ github.event.pull_request.head.sha }}
