name: Test if code is remotely runnable
on: [push]
#clearml-task --project "Github CI/CD" --name cicd_test --script task.py --requirements requirements.txt --skip-task-init --queue default | rg -o 'Task id=(.*) sent' -r '$1'

jobs:
  test-remote-runnable:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ClearML
        run: |
          python -m pip install --upgrade pip clearml
          sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Start the task
        id: launch_task
        run: |
          echo "::set-output name=TASK_ID::$(
            clearml-task --project 'Github CI/CD' --name cicd_test --script task.py --requirements requirements.txt --skip-task-init --queue default | rg -o 'Task id=(.*) sent' -r '$1'
          )"
        env:
          CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      - name: Poll for task progress
        run: python check_clearml_task_running.py ${{ steps.launch_task.outputs.TASK_ID }}
        env:
          CLEARML_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          CLEARML_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}